import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

test('inventory QR module is routed, visible in navigation, and supports local scan runs', () => {
  const app = readFileSync('src/App.tsx', 'utf8');
  const sidebar = readFileSync('src/components/layout/Sidebar.tsx', 'utf8');
  const page = readFileSync('src/pages/InventoryQr.tsx', 'utf8');
  const scanner = readFileSync('src/components/qr/QrScannerDialog.tsx', 'utf8');
  const api = readFileSync('src/services/api.ts', 'utf8');
  const gas = readFileSync('gas/Code.gs', 'utf8');

  assert.match(app, /const InventoryQr = lazy\(\(\) => import\('\.\/pages\/InventoryQr'\)\)/);
  assert.match(app, /path="inventory"/);
  assert.match(sidebar, /path: '\/inventory'/);
  assert.match(sidebar, /name: 'Kiểm kê QR'/);
  assert.match(page, /qlttb\.inventory_runs/);
  assert.match(page, /Tạo đợt kiểm kê/);
  assert.match(page, /QrScannerDialog/);
  assert.match(scanner, /html5-qrcode/);
  assert.match(scanner, /Nhập mã/);
  assert.match(scanner, /startCamera/);
  assert.match(scanner, /Chọn hoặc chụp ảnh có mã/);
  assert.match(scanner, /scanFile/);
  assert.match(page, /Thiết bị chưa quét/);
  assert.match(page, /Sai khoa\/phòng/);
  assert.match(page, /exportCsv/);
  assert.match(page, /saveInventoryRun/);
  assert.match(page, /deleteInventoryRun/);
  assert.match(page, /sheetName/);
  assert.match(page, /Đồng bộ lại/);
  assert.match(page, /Xóa đợt/);
  assert.match(page, /Action không hợp lệ: saveInventoryRun/);
  assert.match(api, /export const saveInventoryRun/);
  assert.match(api, /export const deleteInventoryRun/);
  assert.match(api, /postAction\('saveInventoryRun'/);
  assert.match(api, /postAction\('deleteInventoryRun'/);
  assert.match(gas, /case 'saveInventoryRun'/);
  assert.match(gas, /case 'deleteInventoryRun'/);
  assert.match(gas, /function saveInventoryRun_/);
  assert.match(gas, /function deleteInventoryRun_/);
  assert.match(gas, /function inventorySheetName_/);
  assert.match(gas, /InventoryRuns/);
});
